name: Note.ms Browser Monitor

on:
  repository_dispatch:
    types: [ping_monitor]
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install and Run
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install chromium --with-deps
          python monitor.py
